### ISSUE TITLE
Need tests

### ISSUE THREAD

**Issue by vanarok** [norflin321/font-lh-changer#1]
Current version broken, error on 24 line. I tried change the JetBrains Mono Medium font.

**Comment by tonku321** [comment]
@vanarok here you can take this file, scrip works on it [JetBrains Mono Medium Nerd Font Complete Mono.ttf.zip](https://github.com/norflin321/font-lh-changer/files/8864814/JetBrains.Mono.Medium.Nerd.Font.Complete.Mono.ttf.zip)

**Comment by tonku321** [comment]
#https://github.com/norflin321/font-lh-changer/commit/c5976a49dbe142fd6aae196463f42e84e749a827
